config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Main root
  root 'main#index'
  # Users path
  get '/:username', to: 'users#show', as: 'user'
  patch '/:username', to: 'users#update'
  # Tweet Creation
  resources :tweets, only: [:new, :create]
  # Followers & Following from user
  scope "/:username" do
    resources :followers, param: :username, only: :index, as: 'user_followers'
    resources :following, param: :username, only: :index, as: 'user_following'
  end
  # Following & Unfollowing new users
  resources :following, param: :username, only: [:new, :create, :destroy]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :message, presence: true, length: {maximum: 280}
  has_one_attached :image
  belongs_to :user
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def new
    @tweet = current_user.tweets.new()
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to user_path(current_user.username), notice: "Tweet created & published!"
    else
      render :new
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:message, :image)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
def page_entries_info(collection)
    model_name = collection.respond_to?(:human_name) ? collection.model_name.human : (collection.first&.model_name&.human || '')

    sanitize "Displaying #{model_name} " +
      tag.b("#{collection.offset + 1} - #{[collection.per_page * collection.current_page, collection.total_entries].min}") +
      ' of ' + tag.b(collection.total_entries) +
      ' in total'
end
end

app/views/tweets/_tweet_list.html.erb
<% tweets.each do |tweet| %>
  <%= render partial: "tweets/tweet_template", locals: {user: tweet.user, tweet: tweet} %>
<% end %>
<div class="apple_pagination">
  <div>
    <%= page_entries_info tweets  %>
  </div>
  <div>
    <%= will_paginate tweets, container: false %>
  </div>
</div>

app/views/tweets/_tweet_template.html.erb
<div class="card bg-light text-center mb-3 mx-auto" style="max-width: 50rem;">
  <div class="card-body">
    <%= link_to user.avatar do %>
      <%= image_tag user.avatar.variant(resize_to_fill: [40, 40]).processed, class:"d-inline text-justify" %>
    <% end %>
    <p class="card-title"><p class="font-weight-bold d-inline"><%= user.fullname %></p>, <%= link_to("@"+user.username, user_path(user.username)) %> - <%= tweet.created_at.strftime("%Y-%m-%d - %H:%M") %></p>
    <div class="dropdown-divider"></div>
    <p class="card-text text-justify"><%= tweet.message %> </p>
  </div>
  <% if tweet.image.attached? %>
    <%= link_to tweet.image do %>
      <%= image_tag tweet.image.variant(resize_to_fill: [695, 180]).processed %>
    <% end %>
  <% end %>
    <p class="card-footer"><small class="text-muted">Last edition: <%= tweet.created_at.strftime("%Y-%m-%d - %H:%M") %></small></p>
</div>

app/views/tweets/_twitter_form.html.erb
<%= form_with url: url, model: tweet do |form| %>
  <% if tweet.errors.any? %>
    <div class="alert alert-danger">
      <% tweet.errors.full_messages.each do |message| %>
        <div><%= message %> </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_area :message, class: "form-control", placeholder: "Your awesome message", maxlength:"280", size: "60x5"%>
    <small id="Username" class="form-text text-muted">Just do it!</small>
  </div>
  <div class="form-group">
    <%= form.label :image %>
    <img class="img_upload_field">
    <%= form.file_field :image, accept: 'image/png, image/jpeg', class: "form-control file_upload" %>
    <small id="avatar" class="form-text text-muted">Upload a picture that fits for your tweet.</small>
  </div>
 <%= form.submit "Create tweet", class: "btn btn-primary btn-lg btn-block" %>
 <%= link_to "Back", :back, class: "btn btn-link btn-lg" %>

<% end %>

app/views/tweets/new.html.erb
<h1 class="text-center display-4">New Tweet</h1>
<%= render partial: "twitter_form", locals: {tweet: @tweet, url: tweets_path} %>