config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Main root
  root 'main#index'
  # Users path
  get '/:username', to: 'users#show', as: 'user'
  patch '/:username', to: 'users#update'
  # Tweet Creation
  resources :tweets, only: [:new, :create]
  # Followers & Following from user
  scope "/:username" do
    resources :followers, param: :username, only: :index, as: 'user_followers'
    resources :following, param: :username, only: :index, as: 'user_following'
  end
  # Following & Unfollowing new users
  resources :following, param: :username, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9]*\z/.freeze

  attr_accessor :login
  before_create :set_default_image
  before_create :correct_file_mime_type
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  validates :username, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_USERNAME_REGEX }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  # Uses Truemail Gem to check if the email really exist
  validate :validate_email_layers

  has_many :tweets, dependent: :delete_all

  has_many :follows, dependent: :destroy, primary_key: :username

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow', primary_key: :username
  has_many :followers, through: :follower_relationships, source: :follower, primary_key: :username

  has_many :following_relationships, foreign_key: :user_id, class_name: 'Follow', primary_key: :username
  has_many :following, through: :following_relationships, source: :following, primary_key: :username

  private

  def set_default_image
    self.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default.png')), 
                      filename: 'default-image.png', content_type: 'image/png')
  end

  # Virtual attribute login - can be username or email
  def validate_email_layers
    errors.add(:email, 'Was not found') if !Truemail.valid?(email)
  end

  #overrrides find_first_by_auth_conditions to allow email or password as input
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", 
                               { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def correct_file_mime_type
    # correct_file_mime_type
    #
    # checks that the user uploads a valid image
    if avatar.attached? && !avatar.image?
      avatar.purge if avatar.persisted?
      errors.add(:avatar, 'Image must be a JPG or PNG file')
    end
  end

  public

  def login
    # login
    #
    # returns information about the logged user
    if avatar.attached? && !avatar.image?
    @login || self.username || self.email
  end

  def self.search(search)
    # search
    #
    # search for an specific user name
    if search
      find(:all, :conditions => ['username LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :get_user, only: [:show]
  def show
  end

  def edit
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(current_user.username), notice: 'Updated succesfully'
    else
      render :edit
    end
  end

  private

  def get_user
    @user = User.find_by(username: params[:username])
  end

  def user_params
     params.require(:user).permit(:fullname, :avatar, :description, :username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:show]
  before_action :authenticate_user!, only: [:edit]

  def show
    @tweets = @user.tweets.paginate(page: params[:page], per_page: 10).order('created_at DESC')
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(current_user.username), notice: 'Updated succesfully'
    else
      render :edit
    end
  end

  private

  def get_user
    @user = User.find_by(username: params[:username])
  end

  def user_params
     params.require(:user).permit(:fullname, :avatar, :description, :username)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_user_list.html.erb
<% users.each do |user| %>
  <%= render partial: "users/user_template", locals: {user: user} %>
<% end %>
<div class="apple_pagination">
  <div>
    <%= page_entries_info users  %>
  </div>
  <div>
    <%= will_paginate users, container: false %>
  </div>
</div>

app/views/users/_user_template.html.erb
<div class="card bg-light text-center mb-3 mx-auto" style="max-width: 50rem;">
  <div class="card-body">
    <%= link_to user.avatar do %>
      <%= image_tag user.avatar.variant(resize_to_fill: [40, 40]).processed, class:"d-inline text-justify" %>
    <% end %>
    <p class="card-title"><p class="font-weight-bold d-inline"><%= user.fullname %></p>, (<%= link_to "@"+user.username, user_path(user.username) %>) </p>
    <%= render partial: "following/following_button", locals: {user: user}%>
  </div>
</div>

app/views/users/show.html.erb
<div id="user_profile" class="text-center" >
  <h1 class="display-4">Home page</h1>
  <%= link_to @user.avatar do %>
  <picture>
    <%= image_tag @user.avatar.variant(resize_to_fill: [200, 200], vignette: 0).processed %>
  </picture>
<% end %>
  <h2><%= @user.fullname %></h2>
  <h3>@<%= @user.username %></h3>
  <p><%= @user.description %></p>
    <%= render partial: "following/following_table", locals: {user: @user} %>
    <%= render partial: "following/following_button", locals: {user: @user} %>
  <%= link_to "New Tweet", new_tweet_path, class: "btn btn-primary btn-lg m-3" if user_signed_in? && current_user == @user %>
  <% if @user.tweets.nil? %>
    <h1 class="display-4 text-center">Click on create tweet to start</h1>
  <%else%>
    <%= render partial: "tweets/tweet_list", locals: {tweets: @tweets}%>
  <%end%>
</div>