config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Main root
  root 'main#index'
  # Users path
  get '/:username', to: 'users#show', as: 'user'
  patch '/:username', to: 'users#update'
  # Tweet Creation
  resources :tweets, only: [:new, :create]
  # Followers & Following from user
  scope "/:username" do
    resources :followers, param: :username, only: :index, as: 'user_followers'
    resources :following, param: :username, only: :index, as: 'user_following'
  end
  # Following & Unfollowing new users
  resources :following, param: :username, only: [:new, :create, :destroy]
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]
  before_action :get_user

  def index
    @following = @user.following.paginate(page: params[:page], per_page: 10).order('fullname DESC')
  end

  def new
    @follow = current_user.following_relationships.new()
  end

  def create
    @follow = current_user.following_relationships.new(following_id: params[:username])
    if @follow.save
      user = User.find_by(username: params[:username])
      redirect_to user_path(user.username), notice: "You are now following @#{user.username}"
    else
      render :new
    end
  end

  def destroy
    relation = current_user.following_relationships.find_by(following_id: @user.username)
    if relation.destroy
      redirect_to user_path(@user.username), notice: "You are not following @#{@user.username} anymore"
    end
  end

  private

  def get_user
    @user = User.find_by(username: params[:username])
  end

end

app/helpers/following_helper.rb
module FollowingHelper
  def follow_link_to(user)
    form_with url: following_index_path, method: :post do |form|
      concat form.hidden_field(:username, value: user.username)
      concat form.submit("Follow user", class: "btn btn-primary btn-lg m-3")
    end
  end
end

app/views/following/_follow_button.html.erb
<% if user_signed_in? %>
  <% if (current_user != user) && (!current_user.following.include?(user)) %>
    <%= follow_link_to(user) %>
  <% elsif (current_user.following.include?(user)) %>
    <%= link_to "Unfollow", following_path(user.username), class: "btn btn-danger btn-lg m-3", method: :delete %>
  <% end %>
<% end %>

app/views/following/_follow_table.html.erb
<table class="text-center table table-primary">
  <tr>
    <th scope="col"> <%= link_to 'Followers', user_followers_path(user.username) %> </th>
  <%= link_to user.avatar do %>
    <th scope="col"> <%= link_to 'Following', user_following_index_path(user.username) %> </th>
  <% end %>
  </tr>
  <tr>
    <td> <%= link_to user.followers.length, user_followers_path(user.username) %> </td>
    <td> <%= link_to user.following.length, user_following_index_path(user.username) %> </td>
  </tr>
</table>

app/views/following/_following_button.html.erb
<% if user_signed_in? %>
  <% if (current_user != user) && (!current_user.following.include?(user)) %>
    <%= follow_link_to(user) %>
  <% elsif (current_user.following.include?(user)) %>
    <%= link_to "Unfollow", following_path(user.username), class: "btn btn-danger btn-lg m-3", method: :delete %>
  <% end %>
<% end %>

app/views/following/_following_table.html.erb
<table class="text-center table table-primary">
  <tr>
    <th scope="col"> <%= link_to 'Followers', user_followers_path(user.username) %> </th>
  <%= link_to user.avatar do %>
    <th scope="col"> <%= link_to 'Following', user_following_index_path(user.username) %> </th>
  <% end %>
  </tr>
  <tr>
    <td> <%= link_to user.followers.length, user_followers_path(user.username) %> </td>
    <td> <%= link_to user.following.length, user_following_index_path(user.username) %> </td>
  </tr>
</table>

app/views/following/index.html.erb
<%if user_signed_in? && @user == current_user %>
  <h1 class="display-4 text-center"> You are following </h1>
  <%= link_to "Follow another user", new_following_path, class: "text-center btn btn-link btn-lg btn-block" %>
<% else %>
  <h1 class="display-4 text-center"> <%= @user.username %> is following </h1>
<% end %>
<% if !@following.nil? && @following.length > 0%>
  <%= render partial: "users/user_list", locals: {users: @following}%>
<% else %>
  <h1 class="display-4 text-center"> Nobody yet </h1>
<% end %>

app/views/following/new.html.erb
<h1 class="display-4 text-center">Follow another user</h1>

<%= form_with follow: @follow, url: following_index_path, method: :post do |form| %>

  <% if @follow.errors.any? %>
    <div class="alert alert-danger">
      <% @follow.errors.full_messages.each do |message| %>
        <div><%= message %> </div>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :username %>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">@</span>
      </div>
      <%= form.text_field :username, class: "form-control", placeholder: "johnsmit" %>
    </div>
  </div>
 <%= form.submit "Follow user", class: "btn btn-success btn-lg btn-block" %>
<%end%>